### PR TITLE
Run core specs

### PR DESCRIPTION
**Pull request by sauloperez**
## What

I wanted to try running the core's engine specs as [documented in the README](https://github.com/coopdevs/spree/blob/2-0-4-stable/README.md#running-tests), but few failures arose. That surely worked back at the time Spree 2.0.4 was implemented but although the dependencies stay the same (through the Gemfile), bundler and ruby have also evolved causing these failures.

See below the problems I encountered and why require a patch of our own.

### Rabl version can't be resolved

Using version 1.16.1 I don't know why but bundler doesn't know how to resolve what Rabl version to use. It fails as follows:

```
➜  core (run-core-specs) b rake test_app
Generating dummy Rails application...
Setting up dummy database...
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "rabl":
  In Gemfile:
    spree was resolved to 2.0.4, which depends on
      spree_api (= 2.0.4) was resolved to 2.0.4, which depends on
        rabl (= 0.8.4)

Could not find gem 'rabl (= 0.8.4)', which is required by gem 'spree_api (= 2.0.4)', in any of the sources./home/pau/dev/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/home/pau/dev/spree/core/spec/dummy/config/application.rb:1:in `require'
/home/pau/dev/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/home/pau/dev/spree/core/spec/dummy/Rakefile:5:in `require'
/home/pau/dev/spree/core/spec/dummy/Rakefile:5:in `<top (required)>'
/home/pau/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
/home/pau/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `rabl (= 0.8.4)` required by `spree_api (2.0.4)`/home/pau/dev/spree/core/spec/dummy/config/boot.rb:6:in `<top (required)>'
/home/pau/dev/spree/core/spec/dummy/config/application.rb:1:in `require'
/home/pau/dev/spree/core/spec/dummy/config/application.rb:1:in `<top (required)>'
/home/pau/dev/spree/core/spec/dummy/Rakefile:5:in `require'
/home/pau/dev/spree/core/spec/dummy/Rakefile:5:in `<top (required)>'
/home/pau/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
/home/pau/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Skipping installation no generator to run...
```
The issue https://github.com/spree/spree/issues/8189 lead me to its solution https://github.com/spree/spree/pull/8221/files#diff-04c6e90faac2675aa89e2176d2eec7d8R102. Basically, something got broken on the resolution algorithm :disappointed: 

### Rake's #last_comment

I found again the infamous missing `#last_comment` method from Rake. It's the 100th time I visit[ its Stackoverflow solution](https://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11#35893625). Full details there.

### Ruby 2.2.0 removed `test/unit`

The last one is about the evolution of Ruby. Once the two issue above are fixed, I got a last failure running the specs:

```
➜  core (2-0-4-stable) b rspec spec
Instance method "open" is already defined in Object, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
/home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require': cannot
load such file -- test/unit/assertions (LoadError)
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `bloc
k in require'     
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load
_dependency'                                                                                
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `requ
ire'
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:17:in `rescue in <modul
e:Rails>'       
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:12:in `<module:Rails>'
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:6:in `<module:RSpec>'
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails/adapters.rb:5:in `<top (required)>'
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `requ
ire'                           
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `bloc
k in require'             
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load
_dependency'               
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `requ
ire'                                     
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/rspec-rails-2.14.2/lib/rspec/rails.rb:11:in `<top (required)>'
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `requ
ire'                                 
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `bloc
k in require'               
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load
_dependency'              
        from /home/pau/.rbenv/versions/2.2.7/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `requ
ire'                                  
        from /home/pau/dev/spree/core/spec/spec_helper.rb:18:in `<top (required)>'
```

RSpec Rails relied on it back in 2.14 and so `test/unit/assertions` can't be found. The prove is Ruby's doc; while https://ruby-doc.org/stdlib-2.0.0/libdoc/test/ exists, https://ruby-doc.org/stdlib-2.2.0/libdoc/test does not :100: .

The fix is to use the latest Ruby version containing `test/unit`, which is [2.1.9](https://ruby-doc.org/stdlib-2.1.9/libdoc/test/unit/rdoc/Test/Unit/Assertions.html). See https://github.com/rails/rails/issues/18572 for details.

### CODE REVIEW

**Comment by sauloperez** [comment]
:warning: at this point 8 test examples are failing :red_circle: Check output in: https://gist.github.com/sauloperez/2adc2611923a80a72367fa0bec595197 These will have to be skipped not to mask failures caused by us.

**Comment by oeoeaio** [comment]
Nice work! Is the plan from here to `cherry-pick` any commits we need from our existing step-6b, and use this as the basis for the upgrade?

I wonder what is causing all of those CreditCard validation errors... I can't see how any of the changes you had to make could have caused them.

**Comment by sauloperez** [comment]
> Is the plan from here to cherry-pick any commits we need from our existing step-6b, and use this as the basis for the upgrade?

Yes, the idea is to use this branch `2-0-4-stable` for this iteration of the upgrade. Not sure about `step-6b` wasn't it just a branch we merged into `step-6a` (the one we currently use in OFN)?
EDIT yes, no trace of the branch `step-6b` neither OFN nor Coopdevs remotes.

> I wonder what is causing all of those CreditCard validation errors... I can't see how any of the changes you had to make could have caused them.

The test suite was probably not passing when 2.0.4 was released, I guess 😥

**Review by enricostano — APPROVED** [review]

**Comment by sauloperez** [comment]
We need to hold the discussion about the approach we are taking on the upgrade before we spend any time figuring out why these specs fail. Then, if we all agree it has to be the first thing we do next.

**Pull request merged**
